SET(CTEST_SOURCE_DIRECTORY ${CTEST_SCRIPT_DIRECTORY})
SET(CTEST_BINARY_DIRECTORY ${CTEST_SCRIPT_DIRECTORY}/build/Win_MSVC)

SET(CTEST_CMAKE_COMMAND "C:/Program Files/CMake 2.8/bin/cmake.exe")
SET(CTEST_COMMAND "C:/Program Files/CMake 2.8/bin/ctest.exe -D Continuous")

SET(CTEST_SITE "Fraser Laptop")
SET(CTEST_BUILD_NAME "Win32-MSBuild")

SET(CTEST_CMAKE_GENERATOR "Visual Studio 10")
SET(CTEST_BUILD_CONFIGURATION "Release")
#SET(CTEST_BUILD_OPTIONS "-DWITH_SSH1=ON -WITH_SFTP=ON -DWITH_SERVER=ON -DWITH_ZLIB=ON -DWITH_PCAP=ON -DWITH_GCRYPT=OFF")

SET(WITH_MEMCHECK FALSE)
SET(WITH_COVERAGE FALSE)

#######################################################################

#CTEST_EMPTY_BINARY_DIRECTORY(${CTEST_BINARY_DIRECTORY})

FIND_PROGRAM(CTEST_GIT_COMMAND NAMES git PATHS "C:/Program Files/Git/bin")

IF(NOT EXISTS "${CTEST_SOURCE_DIRECTORY}")
  SET(CTEST_CHECKOUT_COMMAND "${CTEST_GIT_COMMAND} clone git@github.com:maidsafe/MaidSafe-DHT.git ${CTEST_SOURCE_DIRECTORY}")
ENDIF()

SET(CTEST_UPDATE_COMMAND "${CTEST_GIT_COMMAND}")

SET(CTEST_CONFIGURE_COMMAND "\"${CMAKE_COMMAND}\"  -C../../PreloadCache.cmake")
SET(CTEST_CONFIGURE_COMMAND "${CTEST_CONFIGURE_COMMAND} -DCMAKE_BUILD_TYPE:STRING=${CTEST_BUILD_CONFIGURATION}")
#SET(CTEST_CONFIGURE_COMMAND "${CTEST_CONFIGURE_COMMAND} -DWITH_TESTING:BOOL=ON ${CTEST_BUILD_OPTIONS}")
#SET(CTEST_CONFIGURE_COMMAND "${CTEST_CONFIGURE_COMMAND} -G\"${CTEST_CMAKE_GENERATOR}\"")
SET(CTEST_CONFIGURE_COMMAND "${CTEST_CONFIGURE_COMMAND} \"${CTEST_SOURCE_DIRECTORY}\"")

WHILE(1)
  CTEST_START("Continuous")
  CTEST_UPDATE(RETURN_VALUE updated_count)
  IF(${updated_count} GREATER 0)
    CTEST_CONFIGURE()
    CTEST_BUILD()
    CTEST_TEST()
    CTEST_SUBMIT()
  ELSEIF(${updated_count} EQUAL -1)
    BREAK()
  ENDIF()
  CTEST_SLEEP(300)
ENDWHILE()
